In [1]:
import pandas as pd
import numpy as np
import os
import mysql.connector
import logging

In [2]:
dailyoutput = pd.read_csv("data/predict_2022-03-12.csv", encoding='utf-8' )
dailyoutput.garch = dailyoutput.garch * 100
dailyoutput.svr = dailyoutput.svr.str.replace('[','').str.replace(']','').astype(float)
dailyoutput.mlp = dailyoutput.mlp.str.replace('[','').str.replace(']','').astype(float)
dailyoutput.LSTM = dailyoutput.LSTM.str.replace('[','').str.replace(']','').astype(float)

In [3]:
dailyoutput

,Date,Symbol,Exchange,garch,svr,mlp,LSTM
0,2022-03-12 03:38:18.409915,MSFT,NASDAQ,1.495965,0.724224,0.725158,281.508400
1,2022-03-12 03:38:18.409915,INTC,NASDAQ,1.565994,1.182537,1.007658,53.685925
2,2022-03-12 03:38:18.409915,EBAY,NASDAQ,3.650751,1.340539,1.132716,71.075100
3,2022-03-12 03:38:18.409915,XOM,NYSE,2.597452,1.719189,1.675012,56.183563
4,2022-03-12 03:38:18.409915,AAPL,NASDAQ,2.086417,1.013130,1.063341,102.706970
...,...,...,...,...,...,...,...
77,2022-03-12 03:38:18.409915,VNQ,AMEX,0.633106,0.687280,0.650544,99.323840
78,2022-03-12 03:38:18.409915,XHB,AMEX,1.273629,0.392280,0.448115,70.172300
79,2022-03-12 03:38:18.409915,SPY,AMEX,0.324536,0.371944,0.211655,298.113200
80,2022-03-12 03:38:18.409915,QQQ,NASDAQ,0.663115,0.608940,0.715801,290.222200
81,2022-03-12 03:38:18.409915,IWM,AMEX,1.417101,0.667077,0.665888,209.161700

In [4]:
HOST="143.244.188.157"
PORT="3306"
USER="patrick-finProj"
PASSWORD="Pat#21$rick"

try: 
    conn = mysql.connector.connect(
        host=HOST,
        port=PORT,
        user=USER,
        password=PASSWORD,
        database="GlobalMarketData"
    )
    query = f"SELECT Symbol, Date, Exchange, Close, Open, High, Low, Volume FROM histdailyprice3 WHERE Date = (SELECT MAX(Date) FROM histdailyprice3);"
    histdailyprice3 = pd.read_sql(query, conn)
    conn.close()
except Exception as e:
    logging.error("Exception occurred", exc_info=True)

In [5]:
histdailyprice3

,Symbol,Date,Exchange,Close,Open,High,Low,Volume
0,A,2022-03-24,NYSE,136.410,134.890,136.5800,133.590,1346700
1,AA,2022-03-24,NYSE,95.060,91.650,95.4400,91.390,7352200
2,AAA,2022-03-24,AMEX,24.785,24.785,24.7850,24.785,100
3,AAAU,2022-03-24,AMEX,19.500,19.420,19.5399,19.360,451800
4,AAC,2022-03-24,NYSE,9.790,9.790,9.8000,9.765,526300
...,...,...,...,...,...,...,...,...
11137,ZXZZT,2022-03-24,NASDAQ,10.000,10.000,10.0000,10.000,12211
11138,ZY,2022-03-24,NASDAQ,3.200,3.410,3.4500,3.145,792200
11139,ZYME,2022-03-24,NYSE,7.380,7.490,7.5000,7.030,727700
11140,ZYNE,2022-03-24,NASDAQ,2.100,2.000,2.1200,1.990,640200
11141,ZYXI,2022-03-24,NASDAQ,6.360,6.260,6.4100,6.140,344800

In [6]:
prev_day = histdailyprice3[["Symbol", "Close"]]

In [7]:
final = dailyoutput.merge(prev_day, on='Symbol')
final["LSTM_volatilty"] = abs(final["LSTM"] / final["Close"] - 1)
final

,Date,Symbol,Exchange,garch,svr,mlp,LSTM,Close,LSTM_volatilty
0,2022-03-12 03:38:18.409915,MSFT,NASDAQ,1.495965,0.724224,0.725158,281.508400,304.10,0.074290
1,2022-03-12 03:38:18.409915,INTC,NASDAQ,1.565994,1.182537,1.007658,53.685925,51.62,0.040022
2,2022-03-12 03:38:18.409915,EBAY,NASDAQ,3.650751,1.340539,1.132716,71.075100,57.23,0.241920
3,2022-03-12 03:38:18.409915,XOM,NYSE,2.597452,1.719189,1.675012,56.183563,83.38,0.326175
4,2022-03-12 03:38:18.409915,AAPL,NASDAQ,2.086417,1.013130,1.063341,102.706970,174.07,0.409967
...,...,...,...,...,...,...,...,...,...
74,2022-03-12 03:38:18.409915,VNQ,AMEX,0.633106,0.687280,0.650544,99.323840,104.92,0.053337
75,2022-03-12 03:38:18.409915,XHB,AMEX,1.273629,0.392280,0.448115,70.172300,66.26,0.059045
76,2022-03-12 03:38:18.409915,SPY,AMEX,0.324536,0.371944,0.211655,298.113200,450.49,0.338247
77,2022-03-12 03:38:18.409915,QQQ,NASDAQ,0.663115,0.608940,0.715801,290.222200,359.65,0.193043
78,2022-03-12 03:38:18.409915,IWM,AMEX,1.417101,0.667077,0.665888,209.161700,205.84,0.016137

In [8]:
final.loc[0, "Date"]

'2022-03-12 03:38:18.409915'

In [9]:
from datetime import date, timedelta, datetime

In [10]:
today = date.today()
today.strftime("%Y-%m-%d")

'2022-03-25'

In [11]:
final_date = datetime.strptime("2022-03-12", "%Y-%m-%d")

In [12]:
_offsets = (3, 1, 1, 1, 1, 1, 2)
def prev_weekday(adate):
    return adate - timedelta(days=_offsets[adate.weekday()])

In [13]:
prev_weekday(final_date)

datetime.datetime(2022, 3, 11, 0, 0)

In [14]:
def get_price_movement(change):
    if change > 0:
        return 1
    elif change < 0:
        return -1
    else:
        return 0

In [23]:
dailyoutput_df = dailyoutput.copy()
prev_date_df = histdailyprice3.copy()

In [25]:
get_price_movement(dailyoutput_df.loc[:, 'LSTM'] - prev_date_df.loc[:, 'Close'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [16]:
predict_df = dailyoutput.merge(prev_day, on='Symbol')

In [89]:
predict_df

,Date,Symbol,Exchange,garch,svr,mlp,LSTM,Close
0,2022-03-12 03:38:18.409915,HYG,AMEX,0.046882,0.207626,0.185455,87.015305,87.99
1,2022-03-12 03:38:18.409915,LQD,AMEX,0.103898,0.301866,0.223957,135.377980,134.50
2,2022-03-12 03:38:18.409915,EFA,AMEX,0.463297,0.276094,0.207428,79.128810,82.20
3,2022-03-12 03:38:18.409915,EWW,AMEX,1.616411,1.550178,1.552551,48.580135,50.34
4,2022-03-12 03:38:18.409915,EWZ,AMEX,2.667359,1.115023,0.901404,36.732370,36.13
5,2022-03-12 03:38:18.409915,GLD,AMEX,0.675120,0.647084,0.511033,170.547520,169.56
6,2022-03-12 03:38:18.409915,SLV,AMEX,2.019469,1.040315,0.724626,21.223501,22.67
7,2022-03-12 03:38:18.409915,XME,AMEX,4.379625,1.419537,1.270820,43.849262,44.90
8,2022-03-12 03:38:18.409915,XOP,AMEX,5.883919,2.090052,2.069409,80.659870,83.78
9,2022-03-12 03:38:18.409915,XLE,AMEX,2.567002,1.443822,1.262277,47.436153,48.39
10,2022-03-12 03:38:18.409915,DBA,AMEX,0.632131,0.554481,0.545004,19.178852,19.10
11,2022-03-12 03:38:18.409915,IYR,AMEX,2.104482,0.684348,0.690882,97.767580,111.09
12,2022-03-12 03:38:18.409915,VNQ,AMEX,0.633106,0.687280,0.650544,99.323840,110.65
13,2022-03-12 03:38:18.409915,XHB,AMEX,1.273629,0.392280,0.448115,70.172300,78.22
14,2022-03-12 03:38:18.409915,SPY,AMEX,0.324536,0.371944,0.211655,298.113200,452.71
15,2022-03-12 03:38:18.409915,IWM,AMEX,1.417101,0.667077,0.665888,209.161700,227.72

In [97]:
predict_df["close_change"] = predict_df.loc[:, 'LSTM'] - predict_df.loc[:, 'Close']
predict_df["price_movement"] = predict_df["close_change"].apply(get_price_movement)

In [98]:
predict_df

,Date,Symbol,Exchange,garch,svr,mlp,LSTM,Close,close_change,price_movement
0,2022-03-12 03:38:18.409915,HYG,AMEX,0.046882,0.207626,0.185455,87.015305,87.99,-0.974695,-1
1,2022-03-12 03:38:18.409915,LQD,AMEX,0.103898,0.301866,0.223957,135.377980,134.50,0.877980,1
2,2022-03-12 03:38:18.409915,EFA,AMEX,0.463297,0.276094,0.207428,79.128810,82.20,-3.071190,-1
3,2022-03-12 03:38:18.409915,EWW,AMEX,1.616411,1.550178,1.552551,48.580135,50.34,-1.759865,-1
4,2022-03-12 03:38:18.409915,EWZ,AMEX,2.667359,1.115023,0.901404,36.732370,36.13,0.602370,1
5,2022-03-12 03:38:18.409915,GLD,AMEX,0.675120,0.647084,0.511033,170.547520,169.56,0.987520,1
6,2022-03-12 03:38:18.409915,SLV,AMEX,2.019469,1.040315,0.724626,21.223501,22.67,-1.446499,-1
7,2022-03-12 03:38:18.409915,XME,AMEX,4.379625,1.419537,1.270820,43.849262,44.90,-1.050738,-1
8,2022-03-12 03:38:18.409915,XOP,AMEX,5.883919,2.090052,2.069409,80.659870,83.78,-3.120130,-1
9,2022-03-12 03:38:18.409915,XLE,AMEX,2.567002,1.443822,1.262277,47.436153,48.39,-0.953847,-1
10,2022-03-12 03:38:18.409915,DBA,AMEX,0.632131,0.554481,0.545004,19.178852,19.10,0.078852,1
11,2022-03-12 03:38:18.409915,IYR,AMEX,2.104482,0.684348,0.690882,97.767580,111.09,-13.322420,-1
12,2022-03-12 03:38:18.409915,VNQ,AMEX,0.633106,0.687280,0.650544,99.323840,110.65,-11.326160,-1
13,2022-03-12 03:38:18.409915,XHB,AMEX,1.273629,0.392280,0.448115,70.172300,78.22,-8.047700,-1
14,2022-03-12 03:38:18.409915,SPY,AMEX,0.324536,0.371944,0.211655,298.113200,452.71,-154.596800,-1
15,2022-03-12 03:38:18.409915,IWM,AMEX,1.417101,0.667077,0.665888,209.161700,227.72,-18.558300,-1