In [25]:
import pandas as pd
import numpy as np
import os
import mysql.connector
import logging

In [44]:
dailyoutput = pd.read_csv("data/predict_2022-03-12.csv", encoding='utf-8' )
dailyoutput.garch = dailyoutput.garch * 100
dailyoutput.svr = dailyoutput.svr.str.replace('[','').str.replace(']','').astype(float)
dailyoutput.mlp = dailyoutput.mlp.str.replace('[','').str.replace(']','').astype(float)
dailyoutput.LSTM = dailyoutput.LSTM.str.replace('[','').str.replace(']','').astype(float)

In [45]:
dailyoutput

,Date,Symbol,Exchange,garch,svr,mlp,LSTM
0,2022-03-12 03:38:18.409915,MSFT,NASDAQ,1.495965,0.724224,0.725158,281.508400
1,2022-03-12 03:38:18.409915,INTC,NASDAQ,1.565994,1.182537,1.007658,53.685925
2,2022-03-12 03:38:18.409915,EBAY,NASDAQ,3.650751,1.340539,1.132716,71.075100
3,2022-03-12 03:38:18.409915,XOM,NYSE,2.597452,1.719189,1.675012,56.183563
4,2022-03-12 03:38:18.409915,AAPL,NASDAQ,2.086417,1.013130,1.063341,102.706970
...,...,...,...,...,...,...,...
77,2022-03-12 03:38:18.409915,VNQ,AMEX,0.633106,0.687280,0.650544,99.323840
78,2022-03-12 03:38:18.409915,XHB,AMEX,1.273629,0.392280,0.448115,70.172300
79,2022-03-12 03:38:18.409915,SPY,AMEX,0.324536,0.371944,0.211655,298.113200
80,2022-03-12 03:38:18.409915,QQQ,NASDAQ,0.663115,0.608940,0.715801,290.222200
81,2022-03-12 03:38:18.409915,IWM,AMEX,1.417101,0.667077,0.665888,209.161700

In [46]:
HOST="143.244.188.157"
PORT="3306"
USER="patrick-finProj"
PASSWORD="Pat#21$rick"

try: 
    conn = mysql.connector.connect(
        host=HOST,
        port=PORT,
        user=USER,
        password=PASSWORD,
        database="GlobalMarketData"
    )
    query = f"SELECT Symbol, Date, Exchange, Close, Open, High, Low, Volume FROM histdailyprice3 WHERE Date = (SELECT MAX(Date) FROM histdailyprice3);"
    histdailyprice3 = pd.read_sql(query, conn)
    conn.close()
except Exception as e:
    logging.error("Exception occurred", exc_info=True)

In [47]:
histdailyprice3

,Symbol,Date,Exchange,Close,Open,High,Low,Volume
0,AAAU,2021-09-07,AMEX,18.0400,18.0500,17.830,17.8800,181834
1,AAMC,2021-09-07,AMEX,26.9900,27.6500,26.010,26.2500,17793
2,AAU,2021-09-07,AMEX,0.3800,0.4149,0.380,0.4149,793739
3,ABEQ,2021-09-07,AMEX,28.2200,28.2200,27.730,27.7300,4388
4,ACES,2021-09-07,AMEX,70.7800,71.4400,70.690,70.9700,60404
...,...,...,...,...,...,...,...,...
2250,ZHDG,2021-09-07,AMEX,20.5000,20.5600,20.450,20.5400,51255
2251,ZIG,2021-09-07,AMEX,29.1200,29.1200,28.670,28.7200,191481
2252,ZOM,2021-09-07,AMEX,0.6037,0.6100,0.562,0.5805,22233655
2253,ZROZ,2021-09-07,AMEX,149.5400,149.7600,148.650,149.6500,128195
2254,ZSL,2021-09-07,AMEX,25.8100,26.4000,25.640,26.0000,334349

In [48]:
prev_day = histdailyprice3[["Symbol", "Close"]]

In [85]:
final = dailyoutput.merge(prev_day, on='Symbol')
final["LSTM_volatilty"] = abs(final["LSTM"] / final["Close"] - 1)
final

,Date,Symbol,Exchange,garch,svr,mlp,LSTM,Close,LSTM_volatilty
0,2022-03-12 03:38:18.409915,HYG,AMEX,0.046882,0.207626,0.185455,87.015305,87.99,0.011077
1,2022-03-12 03:38:18.409915,LQD,AMEX,0.103898,0.301866,0.223957,135.377980,134.50,0.006528
2,2022-03-12 03:38:18.409915,EFA,AMEX,0.463297,0.276094,0.207428,79.128810,82.20,0.037362
3,2022-03-12 03:38:18.409915,EWW,AMEX,1.616411,1.550178,1.552551,48.580135,50.34,0.034960
4,2022-03-12 03:38:18.409915,EWZ,AMEX,2.667359,1.115023,0.901404,36.732370,36.13,0.016672
5,2022-03-12 03:38:18.409915,GLD,AMEX,0.675120,0.647084,0.511033,170.547520,169.56,0.005824
6,2022-03-12 03:38:18.409915,SLV,AMEX,2.019469,1.040315,0.724626,21.223501,22.67,0.063807
7,2022-03-12 03:38:18.409915,XME,AMEX,4.379625,1.419537,1.270820,43.849262,44.90,0.023402
8,2022-03-12 03:38:18.409915,XOP,AMEX,5.883919,2.090052,2.069409,80.659870,83.78,0.037242
9,2022-03-12 03:38:18.409915,XLE,AMEX,2.567002,1.443822,1.262277,47.436153,48.39,0.019712
10,2022-03-12 03:38:18.409915,DBA,AMEX,0.632131,0.554481,0.545004,19.178852,19.10,0.004128
11,2022-03-12 03:38:18.409915,IYR,AMEX,2.104482,0.684348,0.690882,97.767580,111.09,0.119925
12,2022-03-12 03:38:18.409915,VNQ,AMEX,0.633106,0.687280,0.650544,99.323840,110.65,0.102360
13,2022-03-12 03:38:18.409915,XHB,AMEX,1.273629,0.392280,0.448115,70.172300,78.22,0.102885
14,2022-03-12 03:38:18.409915,SPY,AMEX,0.324536,0.371944,0.211655,298.113200,452.71,0.341492
15,2022-03-12 03:38:18.409915,IWM,AMEX,1.417101,0.667077,0.665888,209.161700,227.72,0.081496

In [82]:
final.loc[0, "Date"]

'2022-03-12 03:38:18.409915'

In [73]:
from datetime import date, timedelta, datetime

In [69]:
today = date.today()
today.strftime("%Y-%m-%d")

'2022-03-15'

In [79]:
final_date = datetime.strptime("2022-03-12", "%Y-%m-%d")

In [78]:
_offsets = (3, 1, 1, 1, 1, 1, 2)
def prev_weekday(adate):
    return adate - timedelta(days=_offsets[adate.weekday()])

In [80]:
prev_weekday(final_date)

datetime.datetime(2022, 3, 11, 0, 0)

In [ ]:
def price_movement(predicted, prev):
    movement = predicted - prev
    if movement > 0:
        return 1
    elif movement < 0:
        return -1
    else:
        return 0

In [ ]:
get_price_movement(dailyoutput_df.loc[:, 'LSTM'], prev_date_df.loc[:, 'Close'])

In [88]:
predict_df = dailyoutput.merge(prev_day, on='Symbol')

In [89]:
predict_df

,Date,Symbol,Exchange,garch,svr,mlp,LSTM,Close
0,2022-03-12 03:38:18.409915,HYG,AMEX,0.046882,0.207626,0.185455,87.015305,87.99
1,2022-03-12 03:38:18.409915,LQD,AMEX,0.103898,0.301866,0.223957,135.377980,134.50
2,2022-03-12 03:38:18.409915,EFA,AMEX,0.463297,0.276094,0.207428,79.128810,82.20
3,2022-03-12 03:38:18.409915,EWW,AMEX,1.616411,1.550178,1.552551,48.580135,50.34
4,2022-03-12 03:38:18.409915,EWZ,AMEX,2.667359,1.115023,0.901404,36.732370,36.13
5,2022-03-12 03:38:18.409915,GLD,AMEX,0.675120,0.647084,0.511033,170.547520,169.56
6,2022-03-12 03:38:18.409915,SLV,AMEX,2.019469,1.040315,0.724626,21.223501,22.67
7,2022-03-12 03:38:18.409915,XME,AMEX,4.379625,1.419537,1.270820,43.849262,44.90
8,2022-03-12 03:38:18.409915,XOP,AMEX,5.883919,2.090052,2.069409,80.659870,83.78
9,2022-03-12 03:38:18.409915,XLE,AMEX,2.567002,1.443822,1.262277,47.436153,48.39
10,2022-03-12 03:38:18.409915,DBA,AMEX,0.632131,0.554481,0.545004,19.178852,19.10
11,2022-03-12 03:38:18.409915,IYR,AMEX,2.104482,0.684348,0.690882,97.767580,111.09
12,2022-03-12 03:38:18.409915,VNQ,AMEX,0.633106,0.687280,0.650544,99.323840,110.65
13,2022-03-12 03:38:18.409915,XHB,AMEX,1.273629,0.392280,0.448115,70.172300,78.22
14,2022-03-12 03:38:18.409915,SPY,AMEX,0.324536,0.371944,0.211655,298.113200,452.71
15,2022-03-12 03:38:18.409915,IWM,AMEX,1.417101,0.667077,0.665888,209.161700,227.72