In [4]:
import pandas as pd
import numpy as np
import os

In [8]:
df = pd.read_csv("data/predict_2022-03-12.csv", encoding='utf-8' )
df.garch = df.garch * 100
df.svr = df.svr.str.replace('[','').str.replace(']','')
df.mlp = df.mlp.str.replace('[','').str.replace(']','')
df.LSTM = df.LSTM.str.replace('[','').str.replace(']','')

In [22]:
df

,Date,Symbol,Exchange,garch,svr,mlp,LSTM
0,2022-03-12 03:38:18.409915,MSFT,NASDAQ,1.495965,0.72422446,0.72515825,281.5084
1,2022-03-12 03:38:18.409915,INTC,NASDAQ,1.565994,1.18253687,1.00765755,53.685925
2,2022-03-12 03:38:18.409915,EBAY,NASDAQ,3.650751,1.340539,1.13271568,71.0751
3,2022-03-12 03:38:18.409915,XOM,NYSE,2.597452,1.71918885,1.67501219,56.183563
4,2022-03-12 03:38:18.409915,AAPL,NASDAQ,2.086417,1.01313011,1.06334141,102.70697
...,...,...,...,...,...,...,...
77,2022-03-12 03:38:18.409915,VNQ,AMEX,0.633106,0.68728044,0.65054449,99.32384
78,2022-03-12 03:38:18.409915,XHB,AMEX,1.273629,0.39227996,0.44811499,70.1723
79,2022-03-12 03:38:18.409915,SPY,AMEX,0.324536,0.37194438,0.21165542,298.1132
80,2022-03-12 03:38:18.409915,QQQ,NASDAQ,0.663115,0.60894032,0.71580094,290.2222
81,2022-03-12 03:38:18.409915,IWM,AMEX,1.417101,0.66707725,0.66588812,209.1617